"""empty message

Revision ID: 26e464f80a91
Revises: 3922dd62ed18
Create Date: 2015-08-05 11:54:40.557069

"""

# revision identifiers, used by Alembic.
revision = '26e464f80a91'
down_revision = '3922dd62ed18'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
